// Code generated by mapgen map; DO NOT EDIT.

package usersv1

import (
	"github.com/kitti12911/lib-util/v3/protoutil"

	userv1 "oas-sandbox/gen/grpc/user/v1"
)

// userFromProto maps userv1.User to User.
func userFromProto(in *userv1.User) User {
	if in == nil {
		return User{}
	}
	return User{
		CreatedAt:   protoutil.TimeFromProto(in.CreatedAt),
		DisplayName: in.DisplayName,
		Email:       in.Email,
		ID:          in.Id,
		Profile:     profileFromProto(in.Profile),
		Status:      userStatusFromProto(in.Status),
		UpdatedAt:   protoutil.TimeFromProto(in.UpdatedAt),
		Username:    in.Username,
	}
}

// addressFromProto maps userv1.UserAddress to Address.
func addressFromProto(in *userv1.UserAddress) *Address {
	if in == nil {
		return nil
	}
	return &Address{
		City:        in.City,
		CountryCode: in.CountryCode,
		Line1:       in.Line1,
		Line2:       in.Line2,
		PostalCode:  in.PostalCode,
		State:       in.State,
	}
}

// profileFromProto maps userv1.UserProfile to Profile.
func profileFromProto(in *userv1.UserProfile) *Profile {
	if in == nil {
		return nil
	}
	return &Profile{
		Address:     addressFromProto(in.Address),
		FirstName:   in.FirstName,
		LastName:    in.LastName,
		PhoneNumber: in.PhoneNumber,
	}
}

// userToProto maps CreateUserRequest to userv1.User.
func userToProto(src CreateUserRequest) *userv1.User {
	return &userv1.User{
		DisplayName: src.DisplayName,
		Email:       src.Email,
		Profile:     profileToProto(src.Profile),
		Status:      toProtoUserStatus(src.Status),
		Username:    src.Username,
	}
}

// addressToProto maps CreateAddress to userv1.UserAddress.
func addressToProto(src *CreateAddress) *userv1.UserAddress {
	if src == nil {
		return nil
	}
	return &userv1.UserAddress{
		City:        src.City,
		CountryCode: src.CountryCode,
		Line1:       src.Line1,
		Line2:       src.Line2,
		PostalCode:  src.PostalCode,
		State:       src.State,
	}
}

// profileToProto maps CreateProfile to userv1.UserProfile.
func profileToProto(src *CreateProfile) *userv1.UserProfile {
	if src == nil {
		return nil
	}
	return &userv1.UserProfile{
		Address:     addressToProto(src.Address),
		FirstName:   src.FirstName,
		LastName:    src.LastName,
		PhoneNumber: src.PhoneNumber,
	}
}

// createUserOutputFromProto wraps userv1.CreateUserResponse into CreateUserOutput.
func createUserOutputFromProto(in *userv1.CreateUserResponse) *CreateUserOutput {
	if in == nil {
		return &CreateUserOutput{}
	}
	return &CreateUserOutput{
		Body: CreateUserResult{
			ID: in.GetId(),
		},
	}
}

// getUserOutputFromProto wraps userv1.GetUserResponse into GetUserOutput.
func getUserOutputFromProto(in *userv1.GetUserResponse) *GetUserOutput {
	if in == nil {
		return &GetUserOutput{}
	}
	return &GetUserOutput{
		Body: userFromProto(in.GetUser()),
	}
}

// listUsersOutputFromProto wraps userv1.ListUsersResponse into ListUsersOutput.
func listUsersOutputFromProto(in *userv1.ListUsersResponse) *ListUsersOutput {
	if in == nil {
		return &ListUsersOutput{}
	}
	users := make([]User, 0, len(in.GetUsers()))
	for _, item := range in.GetUsers() {
		users = append(users, userFromProto(item))
	}
	return &ListUsersOutput{
		Body: UserList{
			Users:      users,
			Page:       int(in.GetPagination().GetPage()),
			PageSize:   int(in.GetPagination().GetPageSize()),
			TotalPages: int(in.GetPagination().GetTotalPages()),
			TotalSize:  int(in.GetPagination().GetTotalSize()),
		},
	}
}

// toProtoUserStatus maps a string to the userv1.UserStatus enum.
func toProtoUserStatus(value string) userv1.UserStatus {
	switch value {
	case "active":
		return userv1.UserStatus_USER_STATUS_ACTIVE
	case "disabled":
		return userv1.UserStatus_USER_STATUS_DISABLED
	case "pending":
		return userv1.UserStatus_USER_STATUS_PENDING
	default:
		return userv1.UserStatus_USER_STATUS_UNSPECIFIED
	}
}

// userStatusFromProto maps the userv1.UserStatus enum to a string.
func userStatusFromProto(value userv1.UserStatus) string {
	switch value {
	case userv1.UserStatus_USER_STATUS_ACTIVE:
		return "active"
	case userv1.UserStatus_USER_STATUS_DISABLED:
		return "disabled"
	case userv1.UserStatus_USER_STATUS_PENDING:
		return "pending"
	default:
		return ""
	}
}
