// Code generated by gen-patch; DO NOT EDIT.

package usersv1

import (
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"

	userv1 "oas-sandbox/gen/grpc/user/v1"
)

func patchUserPatch(input *PatchUserInput) (*userv1.User, *fieldmaskpb.FieldMask) {
	msg := &userv1.User{}
	mask := &fieldmaskpb.FieldMask{}

	if input.Body.Email.Set {
		if !input.Body.Email.Null {
			msg.Email = input.Body.Email.Value
		}
		mask.Paths = append(mask.Paths, "email")
	}
	if input.Body.Username.Set {
		if !input.Body.Username.Null {
			msg.Username = input.Body.Username.Value
		}
		mask.Paths = append(mask.Paths, "username")
	}
	if input.Body.DisplayName.Set {
		if !input.Body.DisplayName.Null {
			msg.DisplayName = &input.Body.DisplayName.Value
		}
		mask.Paths = append(mask.Paths, "display_name")
	}
	if input.Body.Status.Set {
		if !input.Body.Status.Null {
			msg.Status = toProtoUserStatus(input.Body.Status.Value)
		}
		mask.Paths = append(mask.Paths, "status")
	}
	if input.Body.Profile.Set {
		if input.Body.Profile.Null {
			mask.Paths = append(mask.Paths, "profile")
		} else {
			msg.Profile = &userv1.UserProfile{}
			profile := input.Body.Profile.Value
			if profile.FirstName.Set {
				if !profile.FirstName.Null {
					msg.Profile.FirstName = &profile.FirstName.Value
				}
				mask.Paths = append(mask.Paths, "profile.first_name")
			}
			if profile.LastName.Set {
				if !profile.LastName.Null {
					msg.Profile.LastName = &profile.LastName.Value
				}
				mask.Paths = append(mask.Paths, "profile.last_name")
			}
			if profile.PhoneNumber.Set {
				if !profile.PhoneNumber.Null {
					msg.Profile.PhoneNumber = &profile.PhoneNumber.Value
				}
				mask.Paths = append(mask.Paths, "profile.phone_number")
			}
			if profile.Address.Set {
				if profile.Address.Null {
					mask.Paths = append(mask.Paths, "profile.address")
				} else {
					msg.Profile.Address = &userv1.UserAddress{}
					address := profile.Address.Value
					if address.Line1.Set {
						if !address.Line1.Null {
							msg.Profile.Address.Line1 = &address.Line1.Value
						}
						mask.Paths = append(mask.Paths, "profile.address.line1")
					}
					if address.Line2.Set {
						if !address.Line2.Null {
							msg.Profile.Address.Line2 = &address.Line2.Value
						}
						mask.Paths = append(mask.Paths, "profile.address.line2")
					}
					if address.City.Set {
						if !address.City.Null {
							msg.Profile.Address.City = &address.City.Value
						}
						mask.Paths = append(mask.Paths, "profile.address.city")
					}
					if address.State.Set {
						if !address.State.Null {
							msg.Profile.Address.State = &address.State.Value
						}
						mask.Paths = append(mask.Paths, "profile.address.state")
					}
					if address.PostalCode.Set {
						if !address.PostalCode.Null {
							msg.Profile.Address.PostalCode = &address.PostalCode.Value
						}
						mask.Paths = append(mask.Paths, "profile.address.postal_code")
					}
					if address.CountryCode.Set {
						if !address.CountryCode.Null {
							msg.Profile.Address.CountryCode = &address.CountryCode.Value
						}
						mask.Paths = append(mask.Paths, "profile.address.country_code")
					}
				}
			}
		}
	}

	return msg, mask
}
