// Code generated by gen-patch; DO NOT EDIT.

package usersv1

import (
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"

	userv1 "oas-sandbox/gen/grpc/user/v1"
)

func patchUserPatch(input *PatchUserInput) (*userv1.User, *fieldmaskpb.FieldMask) {
	msg := &userv1.User{}
	mask := &fieldmaskpb.FieldMask{}

	if input.Body.Email.Set {
		if !input.Body.Email.Null {
			msg.Email = input.Body.Email.Value
		}
		mask.Paths = append(mask.Paths, "email")
	}
	if input.Body.Username.Set {
		if !input.Body.Username.Null {
			msg.Username = input.Body.Username.Value
		}
		mask.Paths = append(mask.Paths, "username")
	}
	if input.Body.DisplayName.Set {
		if !input.Body.DisplayName.Null {
			msg.DisplayName = &input.Body.DisplayName.Value
		}
		mask.Paths = append(mask.Paths, "display_name")
	}
	if input.Body.Status.Set {
		if !input.Body.Status.Null {
			msg.Status = statusToProto(input.Body.Status.Value)
		}
		mask.Paths = append(mask.Paths, "status")
	}
	if input.Body.Profile.Set {
		if input.Body.Profile.Null {
			mask.Paths = append(mask.Paths, "profile")
		} else {
			msg.Profile = &userv1.UserProfile{}
			if input.Body.Profile.Value.FirstName.Set {
				if !input.Body.Profile.Value.FirstName.Null {
					msg.Profile.FirstName = &input.Body.Profile.Value.FirstName.Value
				}
				mask.Paths = append(mask.Paths, "profile.first_name")
			}
			if input.Body.Profile.Value.LastName.Set {
				if !input.Body.Profile.Value.LastName.Null {
					msg.Profile.LastName = &input.Body.Profile.Value.LastName.Value
				}
				mask.Paths = append(mask.Paths, "profile.last_name")
			}
			if input.Body.Profile.Value.PhoneNumber.Set {
				if !input.Body.Profile.Value.PhoneNumber.Null {
					msg.Profile.PhoneNumber = &input.Body.Profile.Value.PhoneNumber.Value
				}
				mask.Paths = append(mask.Paths, "profile.phone_number")
			}
			if input.Body.Profile.Value.Address.Set {
				if input.Body.Profile.Value.Address.Null {
					mask.Paths = append(mask.Paths, "profile.address")
				} else {
					msg.Profile.Address = &userv1.UserAddress{}
					if input.Body.Profile.Value.Address.Value.Line1.Set {
						if !input.Body.Profile.Value.Address.Value.Line1.Null {
							msg.Profile.Address.Line1 = &input.Body.Profile.Value.Address.Value.Line1.Value
						}
						mask.Paths = append(mask.Paths, "profile.address.line1")
					}
					if input.Body.Profile.Value.Address.Value.Line2.Set {
						if !input.Body.Profile.Value.Address.Value.Line2.Null {
							msg.Profile.Address.Line2 = &input.Body.Profile.Value.Address.Value.Line2.Value
						}
						mask.Paths = append(mask.Paths, "profile.address.line2")
					}
					if input.Body.Profile.Value.Address.Value.City.Set {
						if !input.Body.Profile.Value.Address.Value.City.Null {
							msg.Profile.Address.City = &input.Body.Profile.Value.Address.Value.City.Value
						}
						mask.Paths = append(mask.Paths, "profile.address.city")
					}
					if input.Body.Profile.Value.Address.Value.State.Set {
						if !input.Body.Profile.Value.Address.Value.State.Null {
							msg.Profile.Address.State = &input.Body.Profile.Value.Address.Value.State.Value
						}
						mask.Paths = append(mask.Paths, "profile.address.state")
					}
					if input.Body.Profile.Value.Address.Value.PostalCode.Set {
						if !input.Body.Profile.Value.Address.Value.PostalCode.Null {
							msg.Profile.Address.PostalCode = &input.Body.Profile.Value.Address.Value.PostalCode.Value
						}
						mask.Paths = append(mask.Paths, "profile.address.postal_code")
					}
					if input.Body.Profile.Value.Address.Value.CountryCode.Set {
						if !input.Body.Profile.Value.Address.Value.CountryCode.Null {
							msg.Profile.Address.CountryCode = &input.Body.Profile.Value.Address.Value.CountryCode.Value
						}
						mask.Paths = append(mask.Paths, "profile.address.country_code")
					}
				}
			}
		}
	}

	return msg, mask
}
